  version: '3'

  services:

    ghost:
      image: ghost:1-alpine
      restart: always
      ports:
        - 2368:2368
      depends_on:
        - "db"
      environment:
        # see https://ghost.org/docs/config/
        database__client: mysql
        database__connection__host: db
        database__connection_password: password
        database__connection__database: ghost
      networks:
        - my-network

    db:
      # platform: linux/x86_64 # Caso utilize MacOS, descomente essa linha
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - mysql:/var/lib/mysql
      networks:
        - my-network

  volumes:
    mysql:

  networks:
    my-network: